"""Strictly reqire game_entry platform relationship

Revision ID: 8a29fa552c51
Revises: be7281a4ac73
Create Date: 2024-09-22 14:32:09.790730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a29fa552c51'
down_revision = 'be7281a4ac73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_game_entry_platform_id_platform', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_game_entry_platform_id_platform'), 'platform', ['platform_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_entry_platform_id_platform'), type_='foreignkey')
        batch_op.create_foreign_key('fk_game_entry_platform_id_platform', 'platform', ['platform_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
