"""add platforms table

Revision ID: dc376f5f12cc
Revises: 
Create Date: 2024-09-18 16:33:49.943280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc376f5f12cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_entry_platform_id_platform'), 'platform', ['platform_id'], ['id'])
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_game_entry_platform_id_platform'), type_='foreignkey')
        batch_op.drop_column('platform_id')

    # ### end Alembic commands ###
